Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/RescueModifier:
  Exclude:
    - 'bin/**/*'